<?php

namespace Govnokod\RatingsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RatingTargetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingTargetRepository extends EntityRepository
{
}
