<?php

namespace Govnokod\CommentBundle\Entity;

use Gedmo\Tree\Entity\Repository\MaterializedPathRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends MaterializedPathRepository
{
}
