<?php

namespace Govnokod\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserSignupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSignupRepository extends EntityRepository
{
}
